config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function ($routes) {
	$routes->extensions(['json','xml']);
	$routes->resources('Apis');
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Users', 'action' => 'login', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Articles', 'action' => 'index']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `InflectedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'InflectedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'InflectedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Userjob.php
<?php
namespace App\Model\Entity;

use Cake\Auth\DefaultPasswordHasher;
use Cake\ORM\Entity;
use Cake\ORM\Table;
use DateTime;

/**
 * User Entity.
 */
class Userjob extends Entity
{
    protected function _getDateFormate()
    {
        $myDateTime = new DateTime($this->_properties['datetime']);
        return $myDateTime->format('Y-m-d H:i:s');
    }    

    protected function _getCreatedFormate()
    {
        $myDateTime = new DateTime($this->_properties['createdAt']);
        return $myDateTime->format('Y-m-d H:i:s');
    }
}

src/Model/Table/UserjobsTable.php
<?php
namespace App\Model\Table;

use App\Model\Entity\Adminsetting;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\ORM\TableRegistry;
use Cake\Validation\Validator;
use Cake\Core\Configure;


/**
 * Users Model
 *
 */
class UserjobsTable extends AppTable
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        $this->table('userjobs');
        $this->displayField('id');
        $this->primaryKey('id');
        
        $this->belongsTo('Users',[
            'foreignKey' => 'user_id'
        ]);
        $this->belongsTo('Userwith',[
            'className' => 'Users',
            'foreignKey' => 'user_with'
        ]);
        $this->belongsTo('Services',[
            'foreignKey' => 'service_id'
        ]);
        $this->belongsTo('Subservices',[
            'foreignKey' => 'subservice_id'
        ]);
        $this->belongsTo('Subservicetags',[
            'foreignKey' => 'subservicetag_id'
        ]);
        $this->hasMany('Savedjobs', [
            'foreignKey' => 'job_id',
            'dependent' => true,
            'cascadeCallbacks' => true
        ]);
        $this->hasMany('Jobapplicants', [
            'foreignKey' => 'job_id',
            'dependent' => true,
            'cascadeCallbacks' => true
        ]);
        /*$this->addBehavior('CounterCache', [
            'Users' => ['job_cnt']
        ]);*/
    }
    
    public function saveJob($data=array()){
        $job = $this->newEntity($data);
        
        foreach ($data as $key=>$value){
            $job->$key = $value;
        }
        if ($this->save($job)) {
            return $job->id;
        } else {
            return 0;
        }
    }

    public function updateJob($id, $data) 
    {
        $job = $this->get($id);
        foreach ($data as $key=>$value)
        {
            $job->$key = $value;
        }
        if($this->save($job))
        {
            return $job->id;
        }else {
            return 0;
        }
    }

    public function convertJobToOffer($data)
    {
        $job = $this->get($data['job_id']);
        $condition['Userjobs.id'] = $data['job_id'];
        $applicant_id = $data['applicant_id'];
        $contain = ['Jobapplicants'=> function ($q) use ($applicant_id){
                        return $q
                        ->where(['Jobapplicants.user_id' => $applicant_id]);
                    }];
        $job = $this->find()
        ->where($condition)
        ->contain($contain)
        ->first();
        
        $Usertasks = TableRegistry::get('Usertasks');
        $datatosave['type']                 = 1;
        $datatosave['status']               = '0';
        $datatosave['is_accepted']          = '1';
        if($job['type'] == 1){
            $datatosave['user_id']              = $job['user_with'];
            $datatosave['user_with']            = $job['user_id'];
        }else {
            $datatosave['user_id']              = $job['user_id'];
            $datatosave['user_with']            = $job['user_with'];
        }
        $datatosave['need_serviceid']       = ($job['service_id'] && $job['service_id'] != 0) ? $job['service_id'] : '';
        $datatosave['need_subserviceid']    = ($job['subservice_id'] && $job['subservice_id'] != 0) ? $job['subservice_id'] : 0;
        $datatosave['need_subservicetagid'] = ($job['subservicetag_id'] && $job['subservicetag_id'] != 0) ? $job['subservicetag_id'] : '';
        $datatosave['need_customservice']   = $job['customservice'];
        $datatosave['need_datetime']        = ($job['datetime']) ? $job['datetime'] : $job['jobapplicants'][0]['preferred_datetime'];
        $datatosave['need_location']        = ($job['location']) ? $job['location'] : $job['jobapplicants'][0]['preferred_location'];
        $datatosave['need_note']            = $job['note'];
        
        $datatosave['offer_serviceid']      = Configure::read('PAYMENT_SERVICE_ID');
        $datatosave['offer_subserviceid']   = Configure::read('PAYMENT_SUBSERVICE_ID');
        $datatosave['offer_note']           = $job['jobapplicants'][0]['message'];

        $Apiv4 = TableRegistry::get('Apiv4');
        $amountData = $Apiv4->getAmountData($job['amount']);
        $datatosave['amount']               = ($job['amount'] > 0) ? $job['amount'] : 0.00;
        $datatosave['fee']                  = $amountData['fee'];
        $datatosave['tax']                  = $amountData['tax'];
        $datatosave['promotion_id']         = $job['promotion_id'];
        $datatosave['discount']             = $job['discount'];
        $datatosave['job_id']               = $data['job_id'];
        $datatosave['createdAt']            = date('Y-m-d H:i:s');
        $datatosave['modifiedAt']           = date('Y-m-d H:i:s');

        $result = $Usertasks->add_transaction($datatosave);
        return $result;
    }

    public function getRecordstoController($select=array(), $condition=array(), $contain=array())
    {
        $results = $this->find()
        ->where($condition)
        ->select($select)
        ->contain($contain)
        ->all();
        if($results){
            $results = $results->toArray();
        }
        return $results;
    }
}

src/Controller/UserjobsController.php
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link      http://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 */



namespace App\Controller;
use Cake\ORM\TableRegistry;
use Cake\ORM\Table;
use Cake\Core\Configure;
use Cake\Network\Exception\NotFoundException;
use Cake\View\Exception\MissingTemplateException;
use Cake\Event\Event;
use Cake\I18n\Time;



/**
 * Static content controller
 *
 * This controller will render views from Template/Pages/
 *
 * @link http://book.cakephp.org/3.0/en/controllers/pages-controller.html
 */

class UserjobsController extends AppController {

    /**
     * Displays a view
     *
     * @return void|\Cake\Network\Response
     * @throws \Cake\Network\Exception\NotFoundException When the view file could not
     *   be found or \Cake\View\Exception\MissingTemplateException in debug mode.
     */
  	public function beforeFilter(Event $event){
	    parent::beforeFilter($event);

	    $this->Auth->allow([]);
	}
		
	public function initialize()
	{
		parent::initialize();
		$this->loadComponent('Stripe');
	}
    
    public function joblist() {
        $this->viewBuilder()->layout('admin');
        $listing = array();
        $limit = 10;
        $select = [];
        $conditions = ['Userjobs.type' => 0];
        $contain = [
            'Users'=> function ($q) {
                return $q
                ->select(['Users.id','Users.firstname','Users.lastname']);
            },
            'Userwith'=> function ($q) {
                return $q
                ->select(['Userwith.id','Userwith.firstname','Userwith.lastname']);
            }
        ];
        $requestData=$this->request->query;

        if (isset($requestData['q']) && !empty($requestData['q'])) {
            $conditions['OR'][]['Userjobs.location LIKE'] = '%'.trim($requestData['q']).'%';
            $conditions['OR'][]['Userjobs.customservice LIKE'] = '%'.trim($requestData['q']).'%';
        }
        if (isset($requestData['limit']) && !empty($requestData['limit'])) {
            $limit = $requestData['limit'];
        }
        $this->paginate = [
            'limit' => $limit,
            'select' => $select,
            'conditions' => $conditions,
            'contain' => $contain
        ];
        $data = $this->paginate();
        $this->set(compact('data'));
        $this->set('action','joblist');
        $this->set('csv_export',0);
    }

    public function offerlist() {
        $this->viewBuilder()->layout('admin');
        $listing = array();
        $limit = 10;
        $select = [];
        $conditions = ['Userjobs.type' => 1];
        $contain = [
            'Users'=> function ($q) {
                return $q
                ->select(['Users.id','Users.firstname','Users.lastname']);
            },
            'Userwith'=> function ($q) {
                return $q
                ->select(['Userwith.id','Userwith.firstname','Userwith.lastname']);
            }
        ];
        $requestData=$this->request->query;

        if (isset($requestData['q']) && !empty($requestData['q'])) {
            $conditions['OR'][]['Userjobs.location LIKE'] = '%'.trim($requestData['q']).'%';
            $conditions['OR'][]['Userjobs.customservice LIKE'] = '%'.trim($requestData['q']).'%';
        }
        if (isset($requestData['limit']) && !empty($requestData['limit'])) {
            $limit = $requestData['limit'];
        }
        $this->paginate = [
            'limit' => $limit,
            'select' => $select,
            'conditions' => $conditions,
            'contain' => $contain
        ];
        $data = $this->paginate();
        $this->set(compact('data'));
        $this->set('action','joblist');
        $this->set('csv_export',0);
    }
}

src/Template/Userjobs/joblist.ctp
<link rel="stylesheet" href="<?php echo $this->request->webroot;?>css/custom-with-material.css">

<section class="content-header margin-bottom-lg padding-left-none">
    <h1>
        Marketplace
        <small>Job List</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Jobs List</li>
    </ol>
</section>
<div class="row margin-none">
  <div class="col-xs-12 padding-none">
    <section class="content padding-none"> 
        <div class="box">
            <div class="box-header">
                
            </div>
            <div class="box-body" style="overflow-y:auto;">
                <div class="row table-header-element">                        
                    <?php echo $this->element('top_filter'); ?>
                </div>
                <table id="example1" class="table table-hover">
                    <thead>
                        <tr>
                            <th>Sr. #</th>
                            <th>Jobs ID</th>
                            <th>Owner</th>
                            <th>Assigned To</th>
                            <th>Status</th>
                            <th>Service</th>
                            <th>Date/Time</th>
                            <th>Location</th>
                            <th>Note</th>
                            <th>Amount</th>
                            <th>Discount</th>
                            <th>CreatedAt</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                        $page = $this->Paginator->params()['page'];
                        $limit = $this->Paginator->params()['perPage'];
                        $i = ((($page * $limit) - $limit) * 2) + 1;
                        foreach($data as $key=>$value){ ?>
                        <tr>
                            <td><?php echo $i++;?></td>
                            <td><?php echo $value->id;?></td>
                            <td>
                                <?php echo $value->user->firstname;?>
                            </td>
                            <td>
                                <?php if(isset($value->userwith->firstname)){echo $value->userwith->firstname;}else{ echo "---";}?>
                            </td>
                            <td>
                                <?php if($value->status == 0){echo 'Expired';}elseif ($value->status == 1) {
                                    echo 'Open';
                                }elseif ($value->status == 2) {
                                    echo 'Completed';
                                }elseif ($value->status == 3) {
                                    echo 'Cancelled';
                                }?>
                            </td>
                            <td><?php echo $value->customservice;?></td>
                            <td><?php echo $value->date_formate;?></td>
                            <td><?php echo $value->location;?></td>
                            <td><?php echo $value->note;?></td>
                            <td><?php echo $value->amount;?></td>
                            <td><?php echo $value->discount;?></td>
                            <td><?php echo $value->created_formate;?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
                <?php echo $this->element('pagination'); ?>
            </div>
        </div>
    </section>
  </div>
</div>

src/Template/Userjobs/offerlist.ctp
<link rel="stylesheet" href="<?php echo $this->request->webroot;?>css/custom-with-material.css">

<section class="content-header margin-bottom-lg padding-left-none">
    <h1>
        Marketplace
        <small>Offer List</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Offers List</li>
    </ol>
</section>
<div class="row margin-none">
  <div class="col-xs-12 padding-none">
    <section class="content padding-none"> 
        <div class="box">
            <div class="box-header">
                
            </div>
            <div class="box-body" style="overflow-y:auto;">
                <div class="row table-header-element">                        
                    <?php echo $this->element('top_filter'); ?>
                </div>
                <table id="example1" class="table table-hover">
                    <thead>
                        <tr>
                            <th>Sr. #</th>
                            <th>Offer ID</th>
                            <th>Owner</th>
                            <th>Assigned To</th>
                            <th>Status</th>
                            <th>Service</th>
                            <th>Date/Time</th>
                            <th>Location</th>
                            <th>Note</th>
                            <th>Amount</th>
                            <th>Discount</th>
                            <th>CreatedAt</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                        $page = $this->Paginator->params()['page'];
                        $limit = $this->Paginator->params()['perPage'];
                        $i = ((($page * $limit) - $limit) * 2) + 1;
                        foreach($data as $key=>$value){ ?>
                        <tr>
                            <td><?php echo $i++;?></td>
                            <td><?php echo $value->id;?></td>
                            <td>
                                <?php echo $value->user->firstname;?>
                            </td>
                            <td>
                                <?php if(isset($value->userwith->firstname)){echo $value->userwith->firstname;}else{ echo "---";}?>
                            </td>
                            <td>
                                <?php if($value->status == 0){echo 'Expired';}elseif ($value->status == 1) {
                                    echo 'Open';
                                }elseif ($value->status == 2) {
                                    echo 'Completed';
                                }elseif ($value->status == 3) {
                                    echo 'Cancelled';
                                }?>
                            </td>
                            <td><?php echo $value->customservice;?></td>
                            <td><?php echo $value->date_formate;?></td>
                            <td><?php echo $value->location;?></td>
                            <td><?php echo $value->note;?></td>
                            <td><?php echo $value->amount;?></td>
                            <td><?php echo $value->discount;?></td>
                            <td><?php echo $value->created_formate;?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
                <?php echo $this->element('pagination'); ?>
            </div>
        </div>
    </section>
  </div>
</div>